### PR TITLE
Fix PlotSquared support

### PR DESCRIPTION
**Pull request by N0tMyFaultOG**
- Replaced eol sk repo with new EH repo
- Fixed another dead repo

### CODE REVIEW

**Comment by UtechtDustin** [comment]
@N0tMyFaultOG Thank you for the PR, i will check if it is working.

**Comment by UtechtDustin** [comment]
Dont work for me, i used 1.16 spigot and plotsquared v4.

I will get
```
java.lang.NoClassDefFoundError: com/plotsquared/core/api/PlotAPI
```

**Comment by N0tMyFaultOG** [comment]
> Dont work for me, i used 1.16 spigot and plotsquared v4.
> 
> I get
> 
> ```
> java.lang.NoClassDefFoundError: com/plotsquared/core/api/PlotAPI
> ```

v4 does not support 1.16, nor is v4 supported any longer. v5 is the latest supported version since April 2020.

**Comment by UtechtDustin** [comment]
Okay, that means i will drop support for plotsquared complete ?
I will not pay 15$ to check if you fix works or not.

**Comment by N0tMyFaultOG** [comment]
> Okay, that means i will drop support for plotsquared complete ?
> I will not pay 15$ to check if you fix works or not.

If you want to support v4 and v5, you can easily put the code in an if else tag, and read the version via `PluginDescriptionFile#getDescription()` e.g. or do something similar. 
v5 is as open source as v4 is, you can always build it yourself.

**Comment by UtechtDustin** [comment]
Sure its open source, but i dont want to read how gradle etc. works.
This is a old project which will be updated not so often, as i dont work actively on it.
Which means i dont spend that much time for a other plugin support.

If want to help you can send me a compiled version of the plugins on discord.

**Comment by N0tMyFaultOG** [comment]
> Sure its open source, but i dont want to read how gradle etc. works.
> This is a old project which will be updated not so often, as i dont work actively on it.
> Which means i dont spend that much time for a other plugin support.
> 
> If want to help you can send me a compiled version of the plugins on discord.

A quick look at the README reveals how to build the project.

**Comment by UtechtDustin** [comment]
Sure but i have to install gradle first, i have to find the old api documentation etc.
So if you want to help, add me on discord..

As i already said, this is no active project anymore... so i dont spend that much time for it.

**Comment by N0tMyFaultOG** [comment]
> Sure but i have to install gradle first, i have to find the old api documentation etc.
> So if you want to help, add me on discord..
> 
> As i already said, this is no active project anymore... so i dont spend that much time for it.

I helped you by providing you an up to date patch of the integration, whatever you want to do with the information is up to you.
I don't care enough for v4 anymore to do anything regarding to that, but I'm sure you will figure something out 👍 

Cheers

**Comment by UtechtDustin** [comment]
Okay, no problem then the builders wand has no support for plotsquared until someone will help me out :+1:

**Pull request closed without merging**
